
export const SET_LOCATION_HISTORY = 'SET_LOCATION_HISTORY';

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_SHOP_DETAIL = 'SET_SHOP_DETAIL';
